// ---------------------------------
// This file was generated by Gemini
// ---------------------------------

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:shared_preferences/shared_preferences.dart';

/// Provider for SharedPreferences, initialized in main.dart.
final sharedPrefsProvider = Provider<SharedPreferences>((ref) => throw UnimplementedError());

/// Notifier that manages the application's theme mode (Light/Dark) and persists it.
class ThemeNotifier extends Notifier<ThemeMode> {
  static const _key = 'theme_mode_key';

  @override
  ThemeMode build() {
    final prefs = ref.watch(sharedPrefsProvider);
    final savedTheme = prefs.getString(_key);

    // Load persisted theme preference or default to Light
    if (savedTheme == 'dark') return ThemeMode.dark;
    if (savedTheme == 'light') return ThemeMode.light;

    return ThemeMode.light;
  }

  /// Switches between light and dark themes.
  void toggleTheme(Brightness platformBrightness) {
    final prefs = ref.read(sharedPrefsProvider);
    ThemeMode nextMode;

    // Handle system theme transition logic
    if (state == ThemeMode.system) {
      if (platformBrightness == Brightness.dark) {
        nextMode = ThemeMode.light;
      } else {
        nextMode = ThemeMode.dark;
      }
    } else {
      nextMode = (state == ThemeMode.dark) ? ThemeMode.light : ThemeMode.dark;
    }

    state = nextMode;
    prefs.setString(_key, nextMode == ThemeMode.dark ? 'dark' : 'light');
  }
}

/// Global provider for the application's theme state.
final themeProvider = NotifierProvider<ThemeNotifier, ThemeMode>(ThemeNotifier.new);

/// Configuration class for the application's Light and Dark Material 3 themes.
class AppTheme {
  // Constant colors for UI elements
  static const blueLineColor = Color(0xFF448AFF);
  static const Color myLightBlueBg = Color.fromRGBO(240, 244, 248, 1);
  static const Color myLightBorder = Color.fromRGBO(147, 184, 248, 1.0);
  static const Color myAccentBlue = Colors.blueAccent;

  // Rich text editor (Quill) specific colors
  static const Color quillLightEditorBg = Color.fromRGBO(100, 130, 255, 0.1);
  static const Color quillLightToolbarBg = Color(0xFFF5F5F5);
  static const Color quillLightBorder = Color.fromRGBO(81, 119, 200, 0.5);

  /// Configures the Light theme data.
  static ThemeData get lightTheme {
    return ThemeData(
      useMaterial3: true,
      brightness: Brightness.light,
      // Styling for text selection across the app
      textSelectionTheme: TextSelectionThemeData(
        cursorColor: myAccentBlue,
        selectionColor: myAccentBlue.withAlpha(75),
        selectionHandleColor: myAccentBlue,
      ),
      colorScheme: ColorScheme.fromSeed(
        seedColor: myAccentBlue,
        surface: Colors.white,
        surfaceContainer: myLightBlueBg,
        surfaceContainerHigh: quillLightToolbarBg,
        surfaceContainerLow: quillLightEditorBg,
        outline: quillLightBorder,
        outlineVariant: myLightBorder,
        primary: myAccentBlue,
        onSurface: Colors.black87,
        onSurfaceVariant: Colors.black54,
      ),
      cardTheme: CardThemeData(
        color: myLightBlueBg,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(8),
          side: const BorderSide(color: myLightBorder, width: 2),
        ),
      ),
    );
  }

  /// Configures the Dark theme data.
  static ThemeData get darkTheme {
    return ThemeData(
      useMaterial3: true,
      brightness: Brightness.dark,
      textSelectionTheme: const TextSelectionThemeData(
        cursorColor: Colors.blueAccent,
        selectionColor: Color.fromRGBO(68, 138, 255, 0.4),
        selectionHandleColor: Colors.blueAccent,
      ),
      colorScheme: ColorScheme.dark(
        surface: const Color(0xFF121212),
        surfaceContainer: const Color(0xFF1E1E1E),
        surfaceContainerHigh: const Color(0xFF252525),
        surfaceContainerLow: const Color(0xFF1A1A1A),
        outline: Colors.blueAccent.withAlpha(75),
        outlineVariant: const Color(0xFF333333),
        primary: Colors.blueAccent,
        onSurface: Colors.white,
        onSurfaceVariant: Colors.white70,
      ),
      cardTheme: CardThemeData(
        color: const Color(0xFF1E1E1E),
        surfaceTintColor: Colors.transparent,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(8),
          side: BorderSide(color: Colors.blueAccent.withAlpha(75), width: 2),
        ),
      ),
    );
  }
}