// ---------------------------------
// This file was generated by Gemini
// ---------------------------------

import 'dart:async';
import 'package:flutter/material.dart';

/// A utility class that allows GoRouter to listen to a Stream for refresh triggers.
/// It converts stream events into ChangeNotifier notifications.
class GoRouterRefreshStream extends ChangeNotifier {
GoRouterRefreshStream(Stream<dynamic> stream) {
notifyListeners();
// Subscribe to the stream and notify listeners whenever a new event is emitted
_subscription = stream.asBroadcastStream().listen((dynamic _) => notifyListeners());
}

late final StreamSubscription<dynamic> _subscription;

@override
void dispose() {
// Ensure the subscription is canceled to prevent memory leaks
_subscription.cancel();
super.dispose();
}
}