// ---------------------------------
// This file was generated by Gemini
// ---------------------------------

import 'package:flutter/cupertino.dart';
import 'package:intl/intl.dart';
import 'l10n_extensions.dart';

/// Utility class for formatting dates into human-readable strings.
/// Supports relative formatting for deadlines and creation timestamps.
class DateFormatter {

  /// Formats a deadline relative to the current time.
  /// Handles past deadlines (overdue), today, tomorrow, and future dates.
  static String formatRelativeDeadline(BuildContext context, DateTime dateTime) {
    final now = DateTime.now();
    final localDateTime = dateTime.toLocal();
    final difference = localDateTime.difference(now);

    // Logic for past deadlines
    if (difference.isNegative) {
      if (difference.inDays.abs() == 0) return context.l10n.date_expired_today;
      return context.l10n.date_overdue_days_ago(difference.inDays.abs());
    }

    final today = DateTime(now.year, now.month, now.day);
    final dateToCompare = DateTime(localDateTime.year, localDateTime.month, localDateTime.day);
    final dayDiff = dateToCompare.difference(today).inDays;
    final timeStr = DateFormat('HH:mm').format(localDateTime);

    // Logic for today/tomorrow or near future
    if (dayDiff == 0) return context.l10n.date_today_at(timeStr);
    if (dayDiff == 1) return context.l10n.date_tomorrow_at(timeStr);

    // Relative days for the current month
    if (dayDiff < 30) return context.l10n.date_in_days(dayDiff);

    // Fallback to absolute date for far future
    return DateFormat('dd.MM.yyyy').format(localDateTime);
  }

  /// Formats a creation timestamp into a "time ago" string.
  /// Scales from minutes and hours to days or a full date.
  static String formatCreatedAt(BuildContext context, DateTime dateTime) {
    final now = DateTime.now();
    final diff = now.difference(dateTime.toLocal());

    if (diff.inMinutes < 1) return context.l10n.date_just_now;
    if (diff.inMinutes < 60) return context.l10n.date_mins_ago(diff.inMinutes);
    if (diff.inHours < 24) return context.l10n.date_hours_ago(diff.inHours);
    if (diff.inDays < 7) return context.l10n.date_days_ago(diff.inDays);

    // Fallback to absolute date for older entries
    return DateFormat('dd.MM.yyyy').format(dateTime.toLocal());
  }
}