// ---------------------------------
// This file was generated by Gemini
// ---------------------------------

import 'dart:convert';
import 'package:flutter/cupertino.dart';
import 'package:flutter_quill/flutter_quill.dart';

/// Utility class for handling conversions between the Quill editor's internal format (Delta)
/// and various string representations (JSON or Plain Text).
class QuillUtils {

  /// Converts a stored string into a QuillController.
  /// It automatically handles both JSON Delta format and legacy plain text.
  static QuillController stringToController(String? text) {
    if (text == null || text.isEmpty) {
      return QuillController.basic();
    }

    try {
      // Attempt to parse as JSON (modern Delta format)
      final json = jsonDecode(text);
      return QuillController(
        document: Document.fromJson(json),
        selection: const TextSelection.collapsed(offset: 0),
      );
    } catch (e) {
      // Fallback: If not JSON, treat as legacy plain text
      final doc = Document();
      doc.insert(0, text);
      return QuillController(
        document: doc,
        selection: const TextSelection.collapsed(offset: 0),
        config: QuillControllerConfig(),
      );
    }
  }

  /// Serializes the current state of a QuillController into a JSON string.
  /// This string is intended to be stored in the database.
  static String controllerToString(QuillController controller) {
    return jsonEncode(controller.document.toDelta().toJson());
  }

  /// Converts a stored string (JSON Delta or Plain Text) into a clean plain text preview.
  /// Removes excessive line breaks and trims whitespace.
  static String toPlainText(String? text) {
    if (text == null || text.isEmpty) return "";

    try {
      // Attempt to parse as JSON (modern Delta format)
      final json = jsonDecode(text);
      final doc = Document.fromJson(json);

      // Extract text and sanitize by replacing line breaks with spaces
      return doc.toPlainText().replaceAll('\n', ' ').trim();
    } catch (e) {
      // Fallback: Return legacy text sanitized
      return text.replaceAll('\n', ' ').trim();
    }
  }
}