// ---------------------------------
// This file was generated by Gemini
// ---------------------------------

import 'package:flutter/material.dart';

/// A utility class for defining and checking responsive design breakpoints.
class Responsive {
  /// The width threshold (in pixels) used to distinguish between mobile and desktop layouts.
  static const double mobileBreakpoint = 768;

  /// Returns true if the screen width is smaller than the mobile breakpoint.
  static bool isMobile(BuildContext context) =>
      MediaQuery.of(context).size.width < mobileBreakpoint;

  /// Returns true if the screen width is greater than or equal to the mobile breakpoint.
  static bool isDesktop(BuildContext context) =>
      MediaQuery.of(context).size.width >= mobileBreakpoint;
}

/// A convenience extension on [BuildContext] to allow quick access to responsive properties.
extension ResponsiveExtension on BuildContext {
  /// Shorthand to check if the current layout is mobile.
  bool get isMobile => Responsive.isMobile(this);

  /// Shorthand to check if the current layout is desktop.
  bool get isDesktop => Responsive.isDesktop(this);

  /// Shorthand to retrieve the current screen width.
  double get screenWidth => MediaQuery.of(this).size.width;
}