using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using CheckIn.Api.Bl.Services.Interfaces;
using Microsoft.Extensions.Configuration;
using MimeKit;
using MailKit.Net.Smtp;
using MailKit.Security;
using DnsClient;

namespace CheckIn.Api.Bl.Services;

/// <summary>
/// Implementation of the email service using MailKit and DnsClient.
/// </summary>
public class EmailService(IConfiguration configuration) : IEmailService
{
    /// <summary>
    /// Creates and authenticates an SMTP client based on application settings.
    /// </summary>
    private async Task<SmtpClient> GetConnectedSmtpClientAsync()
    {
        var from = configuration["EmailSettings:Email"];
        var password = configuration["EmailSettings:Password"];
        var host = configuration["EmailSettings:Host"];
        var port = int.Parse(configuration["EmailSettings:Port"] ?? "587");

        var smtp = new SmtpClient();
        await smtp.ConnectAsync(host, port, SecureSocketOptions.StartTls);
        await smtp.AuthenticateAsync(from, password);
        return smtp;
    }

    /// <summary>
    /// Dispatches a single email message.
    /// </summary>
    public async Task SendEmailAsync(string toEmail, string subject, string htmlMessage)
    {
        var from = configuration["EmailSettings:Email"];
        var email = new MimeMessage();
        email.From.Add(new MailboxAddress("CheckIn System", from));
        email.To.Add(MailboxAddress.Parse(toEmail));
        email.Subject = subject;
        email.Body = new BodyBuilder { HtmlBody = htmlMessage }.ToMessageBody();

        using var smtp = await GetConnectedSmtpClientAsync();
        await smtp.SendAsync(email);
        await smtp.DisconnectAsync(true);
    }

    /// <summary>
    /// Processes a list of recipients and sends them either an invitation or a reminder.
    /// </summary>
    public async Task SendBulkEmailsAsync(List<string> emails, string taskHash, string authorName, string taskTitle,
        string? taskDescription, bool isReminder = false)
    {
        var from = configuration["EmailSettings:Email"];

        string templateName = isReminder ? "Reminder.html" : "Invitation.html";
        string subjectPrefix = isReminder ? "Reminder: " : "Invitation for Check-in from ";

        var templatePath = Path.Combine(AppContext.BaseDirectory, "Templates", templateName);
        if (!File.Exists(templatePath))
            throw new FileNotFoundException($"Template not found at: {templatePath}");

        var template = await File.ReadAllTextAsync(templatePath, Encoding.UTF8);

        using var smtp = await GetConnectedSmtpClientAsync();

        var plainDescription = StripQuillDeltaToPlainText(taskDescription ?? "");
        var htmlDescription = plainDescription.Replace("\r\n", "<br>").Replace("\n", "<br>");

        foreach (var toEmail in emails)
        {
            var email = new MimeMessage();
            email.From.Add(new MailboxAddress("CheckIn System", from));
            email.To.Add(MailboxAddress.Parse(toEmail));
            email.Subject = $"{subjectPrefix}{authorName}";

            var baseUrl = configuration["ClientUrl"];
            var inviteLink = $"{baseUrl}{taskHash}";

            var bodyBuilder = new BodyBuilder
            {
                HtmlBody = template
                    .Replace("{AuthorName}", authorName)
                    .Replace("{TaskTitle}", taskTitle)
                    .Replace("{TaskDescription}", string.IsNullOrWhiteSpace(htmlDescription) ? "" : htmlDescription)
                    .Replace("{Link}", inviteLink)
            };
            email.Body = bodyBuilder.ToMessageBody();

            try
            {
                await smtp.SendAsync(email);
                await Task.Delay(500);
            }
            catch (Exception)
            {
                // Silently skip failed individual emails
            }
        }

        await smtp.DisconnectAsync(true);
    }

    // ------------------------------------------------
    // This Function has been generated by Gemini
    // ------------------------------------------------
    /// <summary>
    /// Scans a string for valid email patterns and returns a list of unique addresses.
    /// </summary>
    public List<string> ParseEmails(string rawText)
    {
        if (string.IsNullOrWhiteSpace(rawText)) return new List<string>();

        var regex = new Regex(@"[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}", RegexOptions.Compiled);

        return regex.Matches(rawText)
            .Select(m => m.Value.ToLower().Trim())
            .Distinct()
            .ToList();
    }

    /// <summary>
    /// Validates domain existence via DNS lookup.
    /// </summary>
    public async Task<bool> IsDomainValidAsync(string domain)
    {
        if (string.IsNullOrWhiteSpace(domain)) return false;

        var host = domain.Trim().Split('@').Last();

        return await CheckMxRecordsAsync(host);
    }

    /// <summary>
    /// Validates the domain of a specific email address.
    /// </summary>
    public async Task<bool> IsEmailDomainValidAsync(string email)
    {
        if (string.IsNullOrWhiteSpace(email) || !email.Contains('@')) return false;

        var host = email.Split('@').Last();
        return await CheckMxRecordsAsync(host);
    }

    /// <summary>
    /// Performs an actual DNS query for MX (Mail Exchange) records.
    /// </summary>
    private async Task<bool> CheckMxRecordsAsync(string host)
    {
        try
        {
            var lookup = new LookupClient();
            var result = await lookup.QueryAsync(host, QueryType.MX);
            return !result.HasError && result.Answers.MxRecords().Any();
        }
        catch
        {
            return false;
        }
    }

    // ------------------------------------------------
    // This Function has been generated by Gemini
    // ------------------------------------------------
    /// <summary>
    /// Parses a JSON Delta (from Quill editor) and extracts the plain text content.
    /// Falls back to original text if the input is not a valid Delta JSON.
    /// </summary>
    public string StripQuillDeltaToPlainText(string deltaJson)
    {
        if (string.IsNullOrWhiteSpace(deltaJson)) return string.Empty;

        if (!deltaJson.Trim().StartsWith("[") && !deltaJson.Trim().StartsWith("{"))
            return deltaJson;

        try
        {
            using var doc = JsonDocument.Parse(deltaJson);
            JsonElement opsElement;

            if (doc.RootElement.ValueKind == JsonValueKind.Array)
            {
                opsElement = doc.RootElement;
            }
            else if (doc.RootElement.ValueKind == JsonValueKind.Object &&
                     doc.RootElement.TryGetProperty("ops", out var opsProp))
            {
                opsElement = opsProp;
            }
            else
            {
                return deltaJson;
            }

            var textBuilder = new StringBuilder();
            foreach (var op in opsElement.EnumerateArray())
            {
                if (op.TryGetProperty("insert", out var insertProp))
                {
                    if (insertProp.ValueKind == JsonValueKind.String)
                    {
                        textBuilder.Append(insertProp.GetString());
                    }
                }
            }

            return textBuilder.ToString().Trim();
        }
        catch (Exception)
        {
            return deltaJson;
        }
    }
}