<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\CheckIn.Api.Common\CheckIn.Api.Common.csproj" />
      <ProjectReference Include="..\CheckIn.Api.Dal\CheckIn.Api.Dal.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="AutoMapper" Version="15.0.1" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Facades\" />
      <Folder Include="Mappers\" />
    </ItemGroup>

</Project>
