// ---------------------------------
// This file was generated by Gemini
// ---------------------------------

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

/// A widget that plays a video when hovered over on desktop
/// or when tapped on mobile devices.
class HoverVideoPlayer extends StatefulWidget {
  final String assetPath;

  const HoverVideoPlayer({super.key, required this.assetPath});

  @override
  State<HoverVideoPlayer> createState() => _HoverVideoPlayerState();
}

class _HoverVideoPlayerState extends State<HoverVideoPlayer> {
  late VideoPlayerController _controller;
  bool _isInitialized = false;
  bool _isPlaying = false;

  @override
  void initState() {
    super.initState();
    _initializeController();
  }

  /// Sets up the video player controller with platform-specific loading logic.
  void _initializeController() {
    if (kIsWeb) {
      // For Flutter Web, assets are sometimes better served via direct URL
      // depending on the hosting configuration (e.g., base href).
      final String fileName = widget.assetPath.split('/').last;
      final String baseHref = Uri.base.path.split('/').where((s) => s.isNotEmpty).first;
      final String fullUrl = "${Uri.base.origin}/$baseHref/videos/$fileName";
      _controller = VideoPlayerController.networkUrl(Uri.parse(fullUrl));
    } else {
      _controller = VideoPlayerController.asset(widget.assetPath);
    }

    _controller.initialize().then((_) {
      if (mounted) {
        setState(() {
          _isInitialized = true;
          // Videos must be muted to allow autoplay on most modern browsers
          _controller.setVolume(0);
          _controller.setLooping(true);
        });
      }
    });
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  /// Toggles the play/pause state manually, primarily for touch interactions.
  void _togglePlay() {
    if (_controller.value.isPlaying) {
      _controller.pause();
      setState(() => _isPlaying = false);
    } else {
      _controller.play();
      setState(() => _isPlaying = true);
    }
  }

  @override
  Widget build(BuildContext context) {
    if (!_isInitialized) {
      return const AspectRatio(
        aspectRatio: 16 / 9,
        child: Center(child: CircularProgressIndicator(strokeWidth: 2)),
      );
    }

    // GestureDetector handles taps on mobile devices
    return GestureDetector(
      onTap: _togglePlay,
      child: MouseRegion(
        // MouseRegion handles hover states on desktop browsers
        onEnter: (_) {
          setState(() => _isPlaying = true);
          _controller.play();
        },
        onExit: (_) {
          setState(() => _isPlaying = false);
          _controller.pause();
        },
        child: Stack(
          alignment: Alignment.center,
          children: [
            ClipRect( // Crop
              child: Align(
                alignment: Alignment.center,
                widthFactor: 0.96,
                child: AspectRatio(
                  aspectRatio: _controller.value.aspectRatio,
                  child: VideoPlayer(_controller),
                ),
              ),
            ),
            // Play icon overlay that disappears when the video is playing
            AnimatedOpacity(
              opacity: _isPlaying ? 0.0 : 1.0,
              duration: const Duration(milliseconds: 300),
              child: Container(
                padding: const EdgeInsets.all(12),
                decoration: BoxDecoration(
                  color: Colors.black.withOpacity(0.5),
                  shape: BoxShape.circle,
                ),
                child: const Icon(Icons.play_arrow_rounded, color: Colors.white, size: 40),
              ),
            ),
          ],
        ),
      ),
    );
  }
}